"""Dados exclusivamente fictícios usados pela interface demonstrativa."""

MOCK_OPPORTUNITIES = [
    {
        "id": "mock-petr4-trava-alta",
        "ativo": "PETR4",
        "estrategia": "Trava de alta",
        "tipo_estrutura": "call_debit_spread",
        "score": None,
        "tese": "Alta moderada com rompimento confirmado.",
        "vencimento_dias": 28,
        "strike_comprado": 37.0,
        "strike_vendido": 39.0,
        "premio_pago": 0.65,
        "premio_recebido": 0.23,
        "quantidade": 100,
        "premio_liquido": "R$ 0,42",
        "preco_planejado": 0.42,
        "perda_maxima": "R$ 42 por lote",
        "ganho_maximo": "R$ 158 por lote",
        "break_even": "R$ 37,42",
        "delta": 0.42,
        "theta": -0.03,
        "liquidez_status": "alta",
        "grafico_status": "confirmado",
        "evento_relevante": "não identificado no mock",
        "status": "estudar",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "id": "mock-vale3-put-travada",
        "ativo": "VALE3",
        "estrategia": "Put travada",
        "tipo_estrutura": "bull_put_spread",
        "score": None,
        "tese": "Suporte relevante com prêmio aceitável.",
        "vencimento_dias": 21,
        "strike_comprado": 60.0,
        "strike_vendido": 62.0,
        "premio_pago": 0.25,
        "premio_recebido": 0.70,
        "quantidade": 100,
        "premio_liquido": "R$ 0,45 (mock)",
        "preco_planejado": 0.45,
        "perda_maxima": "R$ 155 por lote",
        "ganho_maximo": "R$ 45 por lote",
        "break_even": "R$ 61,55",
        "delta": -0.31,
        "theta": 0.02,
        "liquidez_status": "média",
        "grafico_status": "confirmado",
        "evento_relevante": "não identificado no mock",
        "status": "acompanhar",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "id": "mock-itub4-venda-coberta",
        "ativo": "ITUB4",
        "estrategia": "Venda coberta",
        "tipo_estrutura": "covered_call",
        "score": None,
        "tese": "Ativo lateral perto de resistência.",
        "vencimento_dias": 35,
        "preco_ativo": 34.20,
        "strike_comprado": "não aplicável",
        "strike_vendido": 35.50,
        "premio_recebido": 0.80,
        "quantidade": 100,
        "premio_liquido": "R$ 0,80 (mock)",
        "preco_planejado": 0.80,
        "perda_maxima": "risco do ativo até zero",
        "ganho_maximo": "R$ 210 por lote",
        "break_even": "R$ 33,40",
        "delta": 0.38,
        "theta": -0.02,
        "liquidez_status": "alta",
        "grafico_status": "pendente",
        "evento_relevante": "não identificado no mock",
        "status": "renda",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
]

MOCK_HEALTHBOX = [
    {"Ativo": "PETR4", "ADR": "2,4%", "ATR": "R$ 0,91", "rVol": "1,32x", "RSI": "61", "RSI 200": "54", "Tendência": "Alta", "Suporte": "R$ 36,20", "Resistência": "R$ 39,10", "Status": "Saudável • MOCK"},
    {"Ativo": "VALE3", "ADR": "2,1%", "ATR": "R$ 1,28", "rVol": "0,94x", "RSI": "47", "RSI 200": "49", "Tendência": "Lateral", "Suporte": "R$ 59,80", "Resistência": "R$ 63,40", "Status": "Neutro • MOCK"},
    {"Ativo": "ITUB4", "ADR": "1,6%", "ATR": "R$ 0,55", "rVol": "1,08x", "RSI": "57", "RSI 200": "59", "Tendência": "Lateral/alta", "Suporte": "R$ 33,70", "Resistência": "R$ 35,60", "Status": "Atenção • MOCK"},
]

MOCK_BULKOWSKI = [
    {"Ativo": "PETR4", "Padrão detectado": "Triângulo ascendente", "Tipo": "Gráfico", "Confirmação": "Sim • MOCK", "Pullback/throwback": "Throwback possível", "Alvo técnico": "R$ 40,20", "Risco de falha": "18% • exemplo", "Status": "Estudar"},
    {"Ativo": "VALE3", "Padrão detectado": "Fundo duplo", "Tipo": "Gráfico", "Confirmação": "Pendente", "Pullback/throwback": "Não detectado", "Alvo técnico": "indisponível", "Risco de falha": "indisponível", "Status": "Esperar"},
    {"Ativo": "ITUB4", "Padrão detectado": "Padrão não detectado", "Tipo": "—", "Confirmação": "—", "Pullback/throwback": "—", "Alvo técnico": "indisponível", "Risco de falha": "indisponível", "Status": "Acompanhar"},
]

MOCK_CHECKLIST = [
    ("🟢", "Gráfico confirma?", "Sim • exemplo"),
    ("🟢", "Liquidez existe?", "Sim • exemplo"),
    ("🟢", "Perda máxima calculada?", "Sim para PETR4"),
    ("🟢", "Operação coberta ou travada?", "Sim"),
    ("🟡", "Valuation confirma?", "fonte ausente"),
    ("🟡", "Evento relevante?", "não verificado"),
    ("🟢", "Prêmio paga o risco?", "Aceitável • exemplo"),
    ("🟡", "Melhor operar ou esperar?", "Estudar"),
]

MOCK_POSITIONS = [
    {"Ativo": "PETR4", "Estratégia": "Trava de alta", "Entrada": "R$ 0,42", "Atual": "R$ 0,88", "L/P": "+R$ 46", "Dias até vencimento": 18, "Status": "Manter", "Alerta": "72% do ganho máx.", "Tipo": "MOCK / EXEMPLO"},
    {"Ativo": "VALE3", "Estratégia": "Put travada", "Entrada": "R$ 0,51", "Atual": "R$ 0,57", "L/P": "+R$ 6", "Dias até vencimento": 12, "Status": "Atenção", "Alerta": "Próxima do strike", "Tipo": "MOCK / EXEMPLO"},
    {"Ativo": "BOVA11", "Estratégia": "Trava de alta", "Entrada": "R$ 0,76", "Atual": "R$ 0,31", "L/P": "-R$ 45", "Dias até vencimento": 7, "Status": "Sair", "Alerta": "Perdeu suporte", "Tipo": "MOCK / EXEMPLO"},
]

MOCK_ALERTS = [
    {"nivel": "success", "titulo": "Realizar", "mensagem": "PETR4 atingiu 72% do ganho máximo"},
    {"nivel": "warning", "titulo": "Atenção", "mensagem": "VALE3 está a 2,1% do strike vendido"},
    {"nivel": "error", "titulo": "Sair agora", "mensagem": "BOVA11 perdeu suporte com 7 dias para vencimento"},
]

MOCK_DATA_SOURCES = [
    {"Campo": "preço PETR4", "Fonte": "mock interno", "Tipo": "mock/exemplo", "Coleta": "não aplicável", "Status": "exemplo"},
    {"Campo": "delta PETR4", "Fonte": "modelo futuro", "Tipo": "estimado", "Coleta": "não aplicado", "Status": "indisponível"},
    {"Campo": "bid/ask", "Fonte": "fonte futura", "Tipo": "coletado", "Coleta": "não aplicado", "Status": "indisponível"},
]

MOCK_ASSET_SNAPSHOTS = [
    {
        "ativo": "PETR4",
        "preco_atual": 37.85,
        "abertura": 37.20,
        "maxima": 38.10,
        "minima": 36.95,
        "fechamento_anterior": 37.05,
        "adr_percent": 2.40,
        "atr_percent": 2.45,
        "rvol": 1.32,
        "rsi": 61.0,
        "rsi_200": 54.0,
        "tendencia": "alta",
        "suporte": 36.20,
        "resistencia": 37.60,
        "rompimento_confirmado": True,
        "volume_confirma": True,
        "pullback_detectado": False,
        "volatilidade_implicita": 31.0,
        "mock_pattern_id": "ascending-triangle",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "ativo": "VALE3",
        "preco_atual": 61.40,
        "abertura": 61.00,
        "maxima": 62.00,
        "minima": 60.60,
        "fechamento_anterior": 61.15,
        "adr_percent": 2.10,
        "atr_percent": 2.00,
        "rvol": 0.94,
        "rsi": 47.0,
        "rsi_200": 49.0,
        "tendencia": "lateral",
        "suporte": 59.80,
        "resistencia": 63.40,
        "rompimento_confirmado": False,
        "volume_confirma": False,
        "pullback_detectado": False,
        "volatilidade_implicita": 28.0,
        "mock_pattern_id": "rectangle",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "ativo": "ITUB4",
        "preco_atual": 34.20,
        "abertura": 34.00,
        "maxima": 34.50,
        "minima": 33.85,
        "fechamento_anterior": 34.05,
        "adr_percent": 1.60,
        "atr_percent": 1.61,
        "rvol": 1.08,
        "rsi": 57.0,
        "rsi_200": 59.0,
        "tendencia": "lateral",
        "suporte": 33.70,
        "resistencia": 35.60,
        "rompimento_confirmado": False,
        "volume_confirma": False,
        "pullback_detectado": False,
        "volatilidade_implicita": 24.0,
        "mock_pattern_id": "rectangle",
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "ativo": "BOVA11",
        "preco_atual": 128.50,
        "abertura": 129.00,
        "maxima": 129.40,
        "minima": 127.80,
        "fechamento_anterior": 129.20,
        "adr_percent": 1.50,
        "atr_percent": 1.80,
        "rvol": 1.25,
        "rsi": 41.0,
        "rsi_200": 48.0,
        "tendencia": "baixa",
        "suporte": 128.80,
        "resistencia": 130.20,
        "rompimento_confirmado": None,
        "volume_confirma": None,
        "pullback_detectado": None,
        "volatilidade_implicita": 18.0,
        "mock_pattern_id": None,
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
    {
        "ativo": "ABEV3",
        "preco_atual": 12.50,
        "abertura": None,
        "maxima": 12.65,
        "minima": None,
        "fechamento_anterior": 12.45,
        "adr_percent": 1.40,
        "atr_percent": None,
        "rvol": None,
        "rsi": None,
        "rsi_200": "indisponível",
        "tendencia": "indefinida",
        "suporte": None,
        "resistencia": 13.00,
        "rompimento_confirmado": None,
        "volume_confirma": None,
        "pullback_detectado": None,
        "volatilidade_implicita": None,
        "mock_pattern_id": None,
        "tipo_dado": "MOCK / EXEMPLO",
        "status_dado": "mock/exemplo",
        "fonte": "mock interno",
        "coleta": "não aplicável",
    },
]

MOCK_MARKET_CONTEXT = {
    "PETR4": {
        "asset_snapshot": {"ativo": "PETR4", "preco_atual": 37.85, "suporte": 36.20, "resistencia": 39.10},
        "healthbox": {"confirmation": "confirma", "status": "saudável no cenário mockado"},
        "bulkowski": {"status": "exemplo estrutural", "confirmacao": "confirmado no mock"},
        "current_mark": 1.21,
        "vencimento_dias": 18,
        "tipo_dado": "MOCK / EXEMPLO",
        "fonte": "mock interno",
    },
    "VALE3": {
        "asset_snapshot": {"ativo": "VALE3", "preco_atual": 61.50, "suporte": 59.80, "resistencia": 63.40},
        "healthbox": {"confirmation": "atenção", "status": "atenção no cenário mockado"},
        "bulkowski": {"status": "inconclusivo", "confirmacao": "inconclusivo no mock"},
        "current_mark": 0.46,
        "vencimento_dias": 8,
        "tipo_dado": "MOCK / EXEMPLO",
        "fonte": "mock interno",
    },
    "BOVA11": {
        "asset_snapshot": {"ativo": "BOVA11", "preco_atual": 127.50, "suporte": 128.80, "resistencia": 130.20},
        "healthbox": {"confirmation": "não confirma", "status": "suporte perdido"},
        "bulkowski": {"status": "padrão não detectado", "confirmacao": "indisponível"},
        "current_mark": 0.30,
        "vencimento_dias": 4,
        "tipo_dado": "MOCK / EXEMPLO",
        "fonte": "mock interno",
    },
}
